version: "2"
services:
  # Backend
  server:
    container_name: server
    build: ./
    command: yarn dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
    restart: unless-stopped
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
